// import type { Metadata } from "next";
// import { IBM_Plex_Sans } from "next/font/google";
// import "./globals.css";

// const ibm = IBM_Plex_Sans({
//     subsets: ["latin"],
//     weight: ["300", "400", "500", "600"],
// });

// export const metadata: Metadata = {
//     title: "UI",
//     description: "Generated by create next app",
// };

// export default function RootLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode;
// }>) {
//     return (
//         <html lang="en">
//             <body className={ibm.className}>{children}</body>
//         </html>
//     );
// }

import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

const ibm = IBM_Plex_Sans({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600"], // Include all desired font weights
});

export const metadata: Metadata = {
    title: "UI",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={ibm.className}>{children}</body>
        </html>
    );
}
